// SPDX-FileCopyrightText: Copyright 2026 The SLSA Authors
// SPDX-License-Identifier: Apache-2.0

package slsa

type (
	SlsaSourceLevel ControlName
)

const (
	SlsaSourceLevel0 SlsaSourceLevel = "SLSA_SOURCE_LEVEL_0"
	SlsaSourceLevel1 SlsaSourceLevel = "SLSA_SOURCE_LEVEL_1"
	SlsaSourceLevel2 SlsaSourceLevel = "SLSA_SOURCE_LEVEL_2"
	SlsaSourceLevel3 SlsaSourceLevel = "SLSA_SOURCE_LEVEL_3"
	SlsaSourceLevel4 SlsaSourceLevel = "SLSA_SOURCE_LEVEL_4"
)

type Level struct {
	Level    uint8
	Controls ControlNameSet
}

var Level0 = ControlNameSet{}

var Level1 = ControlNameSet{
	SLSA_SOURCE_ORG_SCS,
	SLSA_SOURCE_SCS_REPO_ID,
	SLSA_SOURCE_SCS_REVISION_ID,
	SLSA_SOURCE_SCS_DIFF_DISPLAY,
	SLSA_SOURCE_SCS_VSA,
}

var Level2 = ControlNameSet{
	SLSA_SOURCE_ORG_SCS,
	SLSA_SOURCE_ORG_ACCESS_CONTROL,
	SLSA_SOURCE_ORG_SAFE_EXPUNGE,
	SLSA_SOURCE_SCS_REPO_ID,
	SLSA_SOURCE_SCS_REVISION_ID,
	SLSA_SOURCE_SCS_DIFF_DISPLAY,
	SLSA_SOURCE_SCS_VSA,
	SLSA_SOURCE_SCS_HISTORY,
	SLSA_SOURCE_SCS_CONTINUITY,
	SLSA_SOURCE_SCS_IDENTITY,
	SLSA_SOURCE_SCS_PROVENANCE,
}

var Level3 = ControlNameSet{
	SLSA_SOURCE_ORG_SCS,
	SLSA_SOURCE_ORG_ACCESS_CONTROL,
	SLSA_SOURCE_ORG_SAFE_EXPUNGE,
	SLSA_SOURCE_ORG_CONTINUITY,
	SLSA_SOURCE_SCS_REPO_ID,
	SLSA_SOURCE_SCS_REVISION_ID,
	SLSA_SOURCE_SCS_DIFF_DISPLAY,
	SLSA_SOURCE_SCS_VSA,
	SLSA_SOURCE_SCS_HISTORY,
	SLSA_SOURCE_SCS_CONTINUITY,
	SLSA_SOURCE_SCS_IDENTITY,
	SLSA_SOURCE_SCS_PROVENANCE,
	SLSA_SOURCE_SCS_PROTECTED_REFS,
}

var Level4 = ControlNameSet{
	SLSA_SOURCE_ORG_SCS,
	SLSA_SOURCE_ORG_ACCESS_CONTROL,
	SLSA_SOURCE_ORG_SAFE_EXPUNGE,
	SLSA_SOURCE_ORG_CONTINUITY,
	SLSA_SOURCE_SCS_REPO_ID,
	SLSA_SOURCE_SCS_REVISION_ID,
	SLSA_SOURCE_SCS_DIFF_DISPLAY,
	SLSA_SOURCE_SCS_VSA,
	SLSA_SOURCE_SCS_HISTORY,
	SLSA_SOURCE_SCS_CONTINUITY,
	SLSA_SOURCE_SCS_IDENTITY,
	SLSA_SOURCE_SCS_PROVENANCE,
	SLSA_SOURCE_SCS_PROTECTED_REFS,
	SLSA_SOURCE_SCS_TWO_PARTY_REVIEW,
}
