// SPDX-FileCopyrightText: Copyright 2025 The SLSA Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: provenance.proto

package provenance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The predicate that encodes source provenance data.
// The git commit this corresponds to is encoded in the surrounding statement.
type SourceProvenancePred struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The commit preceding 'Commit' in the current context.
	PrevCommit   string                 `protobuf:"bytes,1,opt,name=prev_commit,json=prevCommit,proto3" json:"prev_commit,omitempty"`
	RepoUri      string                 `protobuf:"bytes,2,opt,name=repo_uri,json=repoUri,proto3" json:"repo_uri,omitempty"`
	ActivityType string                 `protobuf:"bytes,3,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	Actor        string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Branch       string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	CreatedOn    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_on,json=createdOn,proto3,oneof" json:"created_on,omitempty"` // TODO: get the author of the PR (if this was from a PR).
	// The controls enabled at the time this commit was pushed.
	Controls      []*Control `protobuf:"bytes,7,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceProvenancePred) Reset() {
	*x = SourceProvenancePred{}
	mi := &file_provenance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceProvenancePred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceProvenancePred) ProtoMessage() {}

func (x *SourceProvenancePred) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceProvenancePred.ProtoReflect.Descriptor instead.
func (*SourceProvenancePred) Descriptor() ([]byte, []int) {
	return file_provenance_proto_rawDescGZIP(), []int{0}
}

func (x *SourceProvenancePred) GetPrevCommit() string {
	if x != nil {
		return x.PrevCommit
	}
	return ""
}

func (x *SourceProvenancePred) GetRepoUri() string {
	if x != nil {
		return x.RepoUri
	}
	return ""
}

func (x *SourceProvenancePred) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *SourceProvenancePred) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *SourceProvenancePred) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *SourceProvenancePred) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *SourceProvenancePred) GetControls() []*Control {
	if x != nil {
		return x.Controls
	}
	return nil
}

type Control struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the control
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The time from which this control has been continuously enforced/observed.
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_provenance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_provenance_proto_rawDescGZIP(), []int{1}
}

func (x *Control) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Control) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

type TagProvenancePred struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RepoUri   string                 `protobuf:"bytes,1,opt,name=repo_uri,json=repoUri,proto3" json:"repo_uri,omitempty"`
	Actor     string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Tag       string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	CreatedOn *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_on,json=createdOn,proto3,oneof" json:"created_on,omitempty"`
	// The tag related controls enabled at the time this tag was created/updated.
	Controls      []*Control    `protobuf:"bytes,7,rep,name=controls,proto3" json:"controls,omitempty"`
	VsaSummaries  []*VsaSummary `protobuf:"bytes,8,rep,name=vsa_summaries,json=vsaSummaries,proto3" json:"vsa_summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagProvenancePred) Reset() {
	*x = TagProvenancePred{}
	mi := &file_provenance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagProvenancePred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagProvenancePred) ProtoMessage() {}

func (x *TagProvenancePred) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagProvenancePred.ProtoReflect.Descriptor instead.
func (*TagProvenancePred) Descriptor() ([]byte, []int) {
	return file_provenance_proto_rawDescGZIP(), []int{2}
}

func (x *TagProvenancePred) GetRepoUri() string {
	if x != nil {
		return x.RepoUri
	}
	return ""
}

func (x *TagProvenancePred) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *TagProvenancePred) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagProvenancePred) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *TagProvenancePred) GetControls() []*Control {
	if x != nil {
		return x.Controls
	}
	return nil
}

func (x *TagProvenancePred) GetVsaSummaries() []*VsaSummary {
	if x != nil {
		return x.VsaSummaries
	}
	return nil
}

// Summary of a summary
type VsaSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceRefs     []string               `protobuf:"bytes,1,rep,name=source_refs,json=sourceRefs,proto3" json:"source_refs,omitempty"`
	VerifiedLevels []string               `protobuf:"bytes,2,rep,name=verified_levels,json=verifiedLevels,proto3" json:"verified_levels,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VsaSummary) Reset() {
	*x = VsaSummary{}
	mi := &file_provenance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VsaSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VsaSummary) ProtoMessage() {}

func (x *VsaSummary) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VsaSummary.ProtoReflect.Descriptor instead.
func (*VsaSummary) Descriptor() ([]byte, []int) {
	return file_provenance_proto_rawDescGZIP(), []int{3}
}

func (x *VsaSummary) GetSourceRefs() []string {
	if x != nil {
		return x.SourceRefs
	}
	return nil
}

func (x *VsaSummary) GetVerifiedLevels() []string {
	if x != nil {
		return x.VerifiedLevels
	}
	return nil
}

var File_provenance_proto protoreflect.FileDescriptor

const file_provenance_proto_rawDesc = "" +
	"\n" +
	"\x10provenance.proto\x123in_toto_attestation.predicates.source_provenance.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x02\n" +
	"\x14SourceProvenancePred\x12\x1f\n" +
	"\vprev_commit\x18\x01 \x01(\tR\n" +
	"prevCommit\x12\x19\n" +
	"\brepo_uri\x18\x02 \x01(\tR\arepoUri\x12#\n" +
	"\ractivity_type\x18\x03 \x01(\tR\factivityType\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x12>\n" +
	"\n" +
	"created_on\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tcreatedOn\x88\x01\x01\x12X\n" +
	"\bcontrols\x18\a \x03(\v2<.in_toto_attestation.predicates.source_provenance.v1.ControlR\bcontrolsB\r\n" +
	"\v_created_on\"O\n" +
	"\aControl\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"\xe5\x02\n" +
	"\x11TagProvenancePred\x12\x19\n" +
	"\brepo_uri\x18\x01 \x01(\tR\arepoUri\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12>\n" +
	"\n" +
	"created_on\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tcreatedOn\x88\x01\x01\x12X\n" +
	"\bcontrols\x18\a \x03(\v2<.in_toto_attestation.predicates.source_provenance.v1.ControlR\bcontrols\x12d\n" +
	"\rvsa_summaries\x18\b \x03(\v2?.in_toto_attestation.predicates.source_provenance.v1.VsaSummaryR\fvsaSummariesB\r\n" +
	"\v_created_on\"V\n" +
	"\n" +
	"VsaSummary\x12\x1f\n" +
	"\vsource_refs\x18\x01 \x03(\tR\n" +
	"sourceRefs\x12'\n" +
	"\x0fverified_levels\x18\x02 \x03(\tR\x0everifiedLevelsB\xe3\x02\n" +
	"7com.in_toto_attestation.predicates.source_provenance.v1B\x0fProvenanceProtoP\x01Z4github.com/slsa-framework/source-tool/pkg/provenance\xa2\x02\x03IPS\xaa\x020InTotoAttestation.Predicates.SourceProvenance.V1\xca\x020InTotoAttestation\\Predicates\\SourceProvenance\\V1\xe2\x02<InTotoAttestation\\Predicates\\SourceProvenance\\V1\\GPBMetadata\xea\x023InTotoAttestation::Predicates::SourceProvenance::V1b\x06proto3"

var (
	file_provenance_proto_rawDescOnce sync.Once
	file_provenance_proto_rawDescData []byte
)

func file_provenance_proto_rawDescGZIP() []byte {
	file_provenance_proto_rawDescOnce.Do(func() {
		file_provenance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provenance_proto_rawDesc), len(file_provenance_proto_rawDesc)))
	})
	return file_provenance_proto_rawDescData
}

var file_provenance_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_provenance_proto_goTypes = []any{
	(*SourceProvenancePred)(nil),  // 0: in_toto_attestation.predicates.source_provenance.v1.SourceProvenancePred
	(*Control)(nil),               // 1: in_toto_attestation.predicates.source_provenance.v1.Control
	(*TagProvenancePred)(nil),     // 2: in_toto_attestation.predicates.source_provenance.v1.TagProvenancePred
	(*VsaSummary)(nil),            // 3: in_toto_attestation.predicates.source_provenance.v1.VsaSummary
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_provenance_proto_depIdxs = []int32{
	4, // 0: in_toto_attestation.predicates.source_provenance.v1.SourceProvenancePred.created_on:type_name -> google.protobuf.Timestamp
	1, // 1: in_toto_attestation.predicates.source_provenance.v1.SourceProvenancePred.controls:type_name -> in_toto_attestation.predicates.source_provenance.v1.Control
	4, // 2: in_toto_attestation.predicates.source_provenance.v1.Control.since:type_name -> google.protobuf.Timestamp
	4, // 3: in_toto_attestation.predicates.source_provenance.v1.TagProvenancePred.created_on:type_name -> google.protobuf.Timestamp
	1, // 4: in_toto_attestation.predicates.source_provenance.v1.TagProvenancePred.controls:type_name -> in_toto_attestation.predicates.source_provenance.v1.Control
	3, // 5: in_toto_attestation.predicates.source_provenance.v1.TagProvenancePred.vsa_summaries:type_name -> in_toto_attestation.predicates.source_provenance.v1.VsaSummary
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_provenance_proto_init() }
func file_provenance_proto_init() {
	if File_provenance_proto != nil {
		return
	}
	file_provenance_proto_msgTypes[0].OneofWrappers = []any{}
	file_provenance_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provenance_proto_rawDesc), len(file_provenance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_provenance_proto_goTypes,
		DependencyIndexes: file_provenance_proto_depIdxs,
		MessageInfos:      file_provenance_proto_msgTypes,
	}.Build()
	File_provenance_proto = out.File
	file_provenance_proto_goTypes = nil
	file_provenance_proto_depIdxs = nil
}
