// SPDX-FileCopyrightText: Copyright 2026 The SLSA Authors
// SPDX-License-Identifier: Apache-2.0

package attest

import (
	"errors"
	"testing"

	"github.com/carabiner-dev/attestation"
	sapi "github.com/carabiner-dev/signer/api/v1"
	"github.com/stretchr/testify/require"
)

// fakeEnvelope is a minimal attestation.Envelope for testing the
// verifier's envelope checks.
type fakeEnvelope struct {
	verifyErr    error
	verification attestation.Verification
}

func (f *fakeEnvelope) GetStatement() attestation.Statement       { return nil }
func (f *fakeEnvelope) GetPredicate() attestation.Predicate       { return nil }
func (f *fakeEnvelope) GetSignatures() []attestation.Signature    { return nil }
func (f *fakeEnvelope) GetCertificate() attestation.Certificate   { return nil }
func (f *fakeEnvelope) GetVerification() attestation.Verification { return f.verification }
func (f *fakeEnvelope) Verify(_ ...any) error                     { return f.verifyErr }

// signedBy returns verification data as generated by the collector
// envelopes after a successful cryptographic check.
func signedBy(issuer, san string) attestation.Verification {
	return &sapi.Verification{
		Signature: &sapi.SignatureVerification{
			Verified: true,
			Identities: []*sapi.Identity{{
				Sigstore: &sapi.IdentitySigstore{
					Issuer:   issuer,
					Identity: san,
				},
			}},
		},
	}
}

func TestVerifyEnvelope(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name    string
		env     attestation.Envelope
		mustErr bool
	}{
		{
			name:    "nil-envelope",
			env:     nil,
			mustErr: true,
		},
		{
			name:    "signature-verification-fails",
			env:     &fakeEnvelope{verifyErr: errors.New("bad signature")},
			mustErr: true,
		},
		{
			// Bare statements return a nil error from Verify but never
			// produce verification data. They must be rejected.
			name:    "unsigned-envelope",
			env:     &fakeEnvelope{},
			mustErr: true,
		},
		{
			name: "unverified-signature",
			env: &fakeEnvelope{verification: &sapi.Verification{
				Signature: &sapi.SignatureVerification{Verified: false},
			}},
			mustErr: true,
		},
		{
			name:    "wrong-identity",
			env:     &fakeEnvelope{verification: signedBy(ExpectedIssuer, "https://github.com/attacker/repo/.github/workflows/fake.yml@refs/heads/main")},
			mustErr: true,
		},
		{
			name:    "wrong-issuer",
			env:     &fakeEnvelope{verification: signedBy("https://accounts.google.com", ExpectedSan)},
			mustErr: true,
		},
		{
			name: "expected-identity",
			env:  &fakeEnvelope{verification: signedBy(ExpectedIssuer, ExpectedSan)},
		},
		{
			// Attestations signed before the repository split are
			// still accepted (issue #255).
			name: "old-identity",
			env:  &fakeEnvelope{verification: signedBy(ExpectedIssuer, OldExpectedSan)},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			err := GetDefaultVerifier().VerifyEnvelope(tc.env)
			if tc.mustErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
		})
	}
}

func TestVerifyEnvelopeCustomIdentity(t *testing.T) {
	t.Parallel()
	custom := NewBndVerifier(VerificationOptions{
		ExpectedIssuer: ExpectedIssuer,
		ExpectedSan:    "https://github.com/example/repo/.github/workflows/sign.yml@refs/heads/main",
	})

	// The pinned identity verifies
	require.NoError(t, custom.VerifyEnvelope(&fakeEnvelope{
		verification: signedBy(ExpectedIssuer, "https://github.com/example/repo/.github/workflows/sign.yml@refs/heads/main"),
	}))

	// ... and without alternates, the default identities don't
	require.Error(t, custom.VerifyEnvelope(&fakeEnvelope{
		verification: signedBy(ExpectedIssuer, ExpectedSan),
	}))
	require.Error(t, custom.VerifyEnvelope(&fakeEnvelope{
		verification: signedBy(ExpectedIssuer, OldExpectedSan),
	}))
}
