// Code generated by counterfeiter. DO NOT EDIT.
package sourcetoolfakes

import (
	"context"
	"sync"

	"github.com/slsa-framework/source-tool/pkg/auth"
	"github.com/slsa-framework/source-tool/pkg/policy"
	"github.com/slsa-framework/source-tool/pkg/slsa"
	"github.com/slsa-framework/source-tool/pkg/sourcetool/models"
	"github.com/slsa-framework/source-tool/pkg/sourcetool/options"
)

type FakeToolImplementation struct {
	CheckForksStub        func(*options.Options) error
	checkForksMutex       sync.RWMutex
	checkForksArgsForCall []FakeToolImplementationCheckForksArgs
	checkForksReturns     struct {
		result1 error
	}
	checkForksReturnsOnCall map[int]struct {
		result1 error
	}
	CheckPolicyForkStub        func(*options.Options) error
	checkPolicyForkMutex       sync.RWMutex
	checkPolicyForkArgsForCall []FakeToolImplementationCheckPolicyForkArgs
	checkPolicyForkReturns     struct {
		result1 error
	}
	checkPolicyForkReturnsOnCall map[int]struct {
		result1 error
	}
	ConfigureControlsStub        func(models.VcsBackend, *models.Repository, []*models.Branch, []models.ControlConfiguration) error
	configureControlsMutex       sync.RWMutex
	configureControlsArgsForCall []FakeToolImplementationConfigureControlsArgs
	configureControlsReturns     struct {
		result1 error
	}
	configureControlsReturnsOnCall map[int]struct {
		result1 error
	}
	CreatePolicyPRStub        func(*auth.Authenticator, *options.Options, *models.Repository, *policy.RepoPolicy) (*models.PullRequest, error)
	createPolicyPRMutex       sync.RWMutex
	createPolicyPRArgsForCall []FakeToolImplementationCreatePolicyPRArgs
	createPolicyPRReturns     struct {
		result1 *models.PullRequest
		result2 error
	}
	createPolicyPRReturnsOnCall map[int]struct {
		result1 *models.PullRequest
		result2 error
	}
	CreateRepositoryForkStub        func(context.Context, *auth.Authenticator, *models.Repository, string) error
	createRepositoryForkMutex       sync.RWMutex
	createRepositoryForkArgsForCall []FakeToolImplementationCreateRepositoryForkArgs
	createRepositoryForkReturns     struct {
		result1 error
	}
	createRepositoryForkReturnsOnCall map[int]struct {
		result1 error
	}
	GetBranchControlsStub        func(context.Context, models.VcsBackend, *models.Branch) (*slsa.ControlSet, error)
	getBranchControlsMutex       sync.RWMutex
	getBranchControlsArgsForCall []FakeToolImplementationGetBranchControlsArgs
	getBranchControlsReturns     struct {
		result1 *slsa.ControlSet
		result2 error
	}
	getBranchControlsReturnsOnCall map[int]struct {
		result1 *slsa.ControlSet
		result2 error
	}
	GetBranchControlsAtCommitStub        func(context.Context, models.VcsBackend, *models.Branch, *models.Commit) (*slsa.ControlSet, error)
	getBranchControlsAtCommitMutex       sync.RWMutex
	getBranchControlsAtCommitArgsForCall []FakeToolImplementationGetBranchControlsAtCommitArgs
	getBranchControlsAtCommitReturns     struct {
		result1 *slsa.ControlSet
		result2 error
	}
	getBranchControlsAtCommitReturnsOnCall map[int]struct {
		result1 *slsa.ControlSet
		result2 error
	}
	GetPolicyStatusStub        func(context.Context, *auth.Authenticator, *options.Options, *models.Repository) (*slsa.Control, error)
	getPolicyStatusMutex       sync.RWMutex
	getPolicyStatusArgsForCall []FakeToolImplementationGetPolicyStatusArgs
	getPolicyStatusReturns     struct {
		result1 *slsa.Control
		result2 error
	}
	getPolicyStatusReturnsOnCall map[int]struct {
		result1 *slsa.Control
		result2 error
	}
	SearchPullRequestStub        func(context.Context, *auth.Authenticator, *models.Repository, string) (*models.PullRequest, error)
	searchPullRequestMutex       sync.RWMutex
	searchPullRequestArgsForCall []FakeToolImplementationSearchPullRequestArgs
	searchPullRequestReturns     struct {
		result1 *models.PullRequest
		result2 error
	}
	searchPullRequestReturnsOnCall map[int]struct {
		result1 *models.PullRequest
		result2 error
	}
	VerifyOptionsForFullOnboardStub        func(*auth.Authenticator, *options.Options) error
	verifyOptionsForFullOnboardMutex       sync.RWMutex
	verifyOptionsForFullOnboardArgsForCall []FakeToolImplementationVerifyOptionsForFullOnboardArgs
	verifyOptionsForFullOnboardReturns     struct {
		result1 error
	}
	verifyOptionsForFullOnboardReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// FakeToolImplementationCheckForksArgs holds the arguments of one call to CheckForks.
type FakeToolImplementationCheckForksArgs struct {
	Arg1 *options.Options
}

// FakeToolImplementationCheckPolicyForkArgs holds the arguments of one call to CheckPolicyFork.
type FakeToolImplementationCheckPolicyForkArgs struct {
	Arg1 *options.Options
}

// FakeToolImplementationConfigureControlsArgs holds the arguments of one call to ConfigureControls.
type FakeToolImplementationConfigureControlsArgs struct {
	Arg1 models.VcsBackend
	Arg2 *models.Repository
	Arg3 []*models.Branch
	Arg4 []models.ControlConfiguration
}

// FakeToolImplementationCreatePolicyPRArgs holds the arguments of one call to CreatePolicyPR.
type FakeToolImplementationCreatePolicyPRArgs struct {
	Arg1 *auth.Authenticator
	Arg2 *options.Options
	Arg3 *models.Repository
	Arg4 *policy.RepoPolicy
}

// FakeToolImplementationCreateRepositoryForkArgs holds the arguments of one call to CreateRepositoryFork.
type FakeToolImplementationCreateRepositoryForkArgs struct {
	Arg1 context.Context
	Arg2 *auth.Authenticator
	Arg3 *models.Repository
	Arg4 string
}

// FakeToolImplementationGetBranchControlsArgs holds the arguments of one call to GetBranchControls.
type FakeToolImplementationGetBranchControlsArgs struct {
	Arg1 context.Context
	Arg2 models.VcsBackend
	Arg3 *models.Branch
}

// FakeToolImplementationGetBranchControlsAtCommitArgs holds the arguments of one call to GetBranchControlsAtCommit.
type FakeToolImplementationGetBranchControlsAtCommitArgs struct {
	Arg1 context.Context
	Arg2 models.VcsBackend
	Arg3 *models.Branch
	Arg4 *models.Commit
}

// FakeToolImplementationGetPolicyStatusArgs holds the arguments of one call to GetPolicyStatus.
type FakeToolImplementationGetPolicyStatusArgs struct {
	Arg1 context.Context
	Arg2 *auth.Authenticator
	Arg3 *options.Options
	Arg4 *models.Repository
}

// FakeToolImplementationSearchPullRequestArgs holds the arguments of one call to SearchPullRequest.
type FakeToolImplementationSearchPullRequestArgs struct {
	Arg1 context.Context
	Arg2 *auth.Authenticator
	Arg3 *models.Repository
	Arg4 string
}

// FakeToolImplementationVerifyOptionsForFullOnboardArgs holds the arguments of one call to VerifyOptionsForFullOnboard.
type FakeToolImplementationVerifyOptionsForFullOnboardArgs struct {
	Arg1 *auth.Authenticator
	Arg2 *options.Options
}

func (fake *FakeToolImplementation) CheckForks(arg1 *options.Options) error {
	fake.checkForksMutex.Lock()
	ret, specificReturn := fake.checkForksReturnsOnCall[len(fake.checkForksArgsForCall)]
	fake.checkForksArgsForCall = append(fake.checkForksArgsForCall, FakeToolImplementationCheckForksArgs{arg1})
	stub := fake.CheckForksStub
	fakeReturns := fake.checkForksReturns
	fake.recordInvocation("CheckForks", []interface{}{arg1})
	fake.checkForksMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeToolImplementation) CheckForksCallCount() int {
	fake.checkForksMutex.RLock()
	defer fake.checkForksMutex.RUnlock()
	return len(fake.checkForksArgsForCall)
}

func (fake *FakeToolImplementation) CheckForksCalls(stub func(*options.Options) error) {
	fake.checkForksMutex.Lock()
	defer fake.checkForksMutex.Unlock()
	fake.CheckForksStub = stub
}

func (fake *FakeToolImplementation) CheckForksArgsForCall(i int) *options.Options {
	fake.checkForksMutex.RLock()
	defer fake.checkForksMutex.RUnlock()
	argsForCall := fake.checkForksArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeToolImplementation) CheckForksArgs() []FakeToolImplementationCheckForksArgs {
	fake.checkForksMutex.RLock()
	defer fake.checkForksMutex.RUnlock()
	args := make([]FakeToolImplementationCheckForksArgs, len(fake.checkForksArgsForCall))
	copy(args, fake.checkForksArgsForCall)
	return args
}

func (fake *FakeToolImplementation) CheckForksReturns(result1 error) {
	fake.checkForksMutex.Lock()
	defer fake.checkForksMutex.Unlock()
	fake.CheckForksStub = nil
	fake.checkForksReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolImplementation) CheckForksReturnsOnCall(i int, result1 error) {
	fake.checkForksMutex.Lock()
	defer fake.checkForksMutex.Unlock()
	fake.CheckForksStub = nil
	if fake.checkForksReturnsOnCall == nil {
		fake.checkForksReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.checkForksReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolImplementation) CheckPolicyFork(arg1 *options.Options) error {
	fake.checkPolicyForkMutex.Lock()
	ret, specificReturn := fake.checkPolicyForkReturnsOnCall[len(fake.checkPolicyForkArgsForCall)]
	fake.checkPolicyForkArgsForCall = append(fake.checkPolicyForkArgsForCall, FakeToolImplementationCheckPolicyForkArgs{arg1})
	stub := fake.CheckPolicyForkStub
	fakeReturns := fake.checkPolicyForkReturns
	fake.recordInvocation("CheckPolicyFork", []interface{}{arg1})
	fake.checkPolicyForkMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeToolImplementation) CheckPolicyForkCallCount() int {
	fake.checkPolicyForkMutex.RLock()
	defer fake.checkPolicyForkMutex.RUnlock()
	return len(fake.checkPolicyForkArgsForCall)
}

func (fake *FakeToolImplementation) CheckPolicyForkCalls(stub func(*options.Options) error) {
	fake.checkPolicyForkMutex.Lock()
	defer fake.checkPolicyForkMutex.Unlock()
	fake.CheckPolicyForkStub = stub
}

func (fake *FakeToolImplementation) CheckPolicyForkArgsForCall(i int) *options.Options {
	fake.checkPolicyForkMutex.RLock()
	defer fake.checkPolicyForkMutex.RUnlock()
	argsForCall := fake.checkPolicyForkArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeToolImplementation) CheckPolicyForkArgs() []FakeToolImplementationCheckPolicyForkArgs {
	fake.checkPolicyForkMutex.RLock()
	defer fake.checkPolicyForkMutex.RUnlock()
	args := make([]FakeToolImplementationCheckPolicyForkArgs, len(fake.checkPolicyForkArgsForCall))
	copy(args, fake.checkPolicyForkArgsForCall)
	return args
}

func (fake *FakeToolImplementation) CheckPolicyForkReturns(result1 error) {
	fake.checkPolicyForkMutex.Lock()
	defer fake.checkPolicyForkMutex.Unlock()
	fake.CheckPolicyForkStub = nil
	fake.checkPolicyForkReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolImplementation) CheckPolicyForkReturnsOnCall(i int, result1 error) {
	fake.checkPolicyForkMutex.Lock()
	defer fake.checkPolicyForkMutex.Unlock()
	fake.CheckPolicyForkStub = nil
	if fake.checkPolicyForkReturnsOnCall == nil {
		fake.checkPolicyForkReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.checkPolicyForkReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolImplementation) ConfigureControls(arg1 models.VcsBackend, arg2 *models.Repository, arg3 []*models.Branch, arg4 []models.ControlConfiguration) error {
	var arg3Copy []*models.Branch
	if arg3 != nil {
		arg3Copy = make([]*models.Branch, len(arg3))
		copy(arg3Copy, arg3)
	}
	var arg4Copy []models.ControlConfiguration
	if arg4 != nil {
		arg4Copy = make([]models.ControlConfiguration, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.configureControlsMutex.Lock()
	ret, specificReturn := fake.configureControlsReturnsOnCall[len(fake.configureControlsArgsForCall)]
	fake.configureControlsArgsForCall = append(fake.configureControlsArgsForCall, FakeToolImplementationConfigureControlsArgs{arg1, arg2, arg3Copy, arg4Copy})
	stub := fake.ConfigureControlsStub
	fakeReturns := fake.configureControlsReturns
	fake.recordInvocation("ConfigureControls", []interface{}{arg1, arg2, arg3Copy, arg4Copy})
	fake.configureControlsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeToolImplementation) ConfigureControlsCallCount() int {
	fake.configureControlsMutex.RLock()
	defer fake.configureControlsMutex.RUnlock()
	return len(fake.configureControlsArgsForCall)
}

func (fake *FakeToolImplementation) ConfigureControlsCalls(stub func(models.VcsBackend, *models.Repository, []*models.Branch, []models.ControlConfiguration) error) {
	fake.configureControlsMutex.Lock()
	defer fake.configureControlsMutex.Unlock()
	fake.ConfigureControlsStub = stub
}

func (fake *FakeToolImplementation) ConfigureControlsArgsForCall(i int) (models.VcsBackend, *models.Repository, []*models.Branch, []models.ControlConfiguration) {
	fake.configureControlsMutex.RLock()
	defer fake.configureControlsMutex.RUnlock()
	argsForCall := fake.configureControlsArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeToolImplementation) ConfigureControlsArgs() []FakeToolImplementationConfigureControlsArgs {
	fake.configureControlsMutex.RLock()
	defer fake.configureControlsMutex.RUnlock()
	args := make([]FakeToolImplementationConfigureControlsArgs, len(fake.configureControlsArgsForCall))
	copy(args, fake.configureControlsArgsForCall)
	return args
}

func (fake *FakeToolImplementation) ConfigureControlsReturns(result1 error) {
	fake.configureControlsMutex.Lock()
	defer fake.configureControlsMutex.Unlock()
	fake.ConfigureControlsStub = nil
	fake.configureControlsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolImplementation) ConfigureControlsReturnsOnCall(i int, result1 error) {
	fake.configureControlsMutex.Lock()
	defer fake.configureControlsMutex.Unlock()
	fake.ConfigureControlsStub = nil
	if fake.configureControlsReturnsOnCall == nil {
		fake.configureControlsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.configureControlsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolImplementation) CreatePolicyPR(arg1 *auth.Authenticator, arg2 *options.Options, arg3 *models.Repository, arg4 *policy.RepoPolicy) (*models.PullRequest, error) {
	fake.createPolicyPRMutex.Lock()
	ret, specificReturn := fake.createPolicyPRReturnsOnCall[len(fake.createPolicyPRArgsForCall)]
	fake.createPolicyPRArgsForCall = append(fake.createPolicyPRArgsForCall, FakeToolImplementationCreatePolicyPRArgs{arg1, arg2, arg3, arg4})
	stub := fake.CreatePolicyPRStub
	fakeReturns := fake.createPolicyPRReturns
	fake.recordInvocation("CreatePolicyPR", []interface{}{arg1, arg2, arg3, arg4})
	fake.createPolicyPRMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeToolImplementation) CreatePolicyPRCallCount() int {
	fake.createPolicyPRMutex.RLock()
	defer fake.createPolicyPRMutex.RUnlock()
	return len(fake.createPolicyPRArgsForCall)
}

func (fake *FakeToolImplementation) CreatePolicyPRCalls(stub func(*auth.Authenticator, *options.Options, *models.Repository, *policy.RepoPolicy) (*models.PullRequest, error)) {
	fake.createPolicyPRMutex.Lock()
	defer fake.createPolicyPRMutex.Unlock()
	fake.CreatePolicyPRStub = stub
}

func (fake *FakeToolImplementation) CreatePolicyPRArgsForCall(i int) (*auth.Authenticator, *options.Options, *models.Repository, *policy.RepoPolicy) {
	fake.createPolicyPRMutex.RLock()
	defer fake.createPolicyPRMutex.RUnlock()
	argsForCall := fake.createPolicyPRArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeToolImplementation) CreatePolicyPRArgs() []FakeToolImplementationCreatePolicyPRArgs {
	fake.createPolicyPRMutex.RLock()
	defer fake.createPolicyPRMutex.RUnlock()
	args := make([]FakeToolImplementationCreatePolicyPRArgs, len(fake.createPolicyPRArgsForCall))
	copy(args, fake.createPolicyPRArgsForCall)
	return args
}

func (fake *FakeToolImplementation) CreatePolicyPRReturns(result1 *models.PullRequest, result2 error) {
	fake.createPolicyPRMutex.Lock()
	defer fake.createPolicyPRMutex.Unlock()
	fake.CreatePolicyPRStub = nil
	fake.createPolicyPRReturns = struct {
		result1 *models.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeToolImplementation) CreatePolicyPRReturnsOnCall(i int, result1 *models.PullRequest, result2 error) {
	fake.createPolicyPRMutex.Lock()
	defer fake.createPolicyPRMutex.Unlock()
	fake.CreatePolicyPRStub = nil
	if fake.createPolicyPRReturnsOnCall == nil {
		fake.createPolicyPRReturnsOnCall = make(map[int]struct {
			result1 *models.PullRequest
			result2 error
		})
	}
	fake.createPolicyPRReturnsOnCall[i] = struct {
		result1 *models.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeToolImplementation) CreateRepositoryFork(arg1 context.Context, arg2 *auth.Authenticator, arg3 *models.Repository, arg4 string) error {
	fake.createRepositoryForkMutex.Lock()
	ret, specificReturn := fake.createRepositoryForkReturnsOnCall[len(fake.createRepositoryForkArgsForCall)]
	fake.createRepositoryForkArgsForCall = append(fake.createRepositoryForkArgsForCall, FakeToolImplementationCreateRepositoryForkArgs{arg1, arg2, arg3, arg4})
	stub := fake.CreateRepositoryForkStub
	fakeReturns := fake.createRepositoryForkReturns
	fake.recordInvocation("CreateRepositoryFork", []interface{}{arg1, arg2, arg3, arg4})
	fake.createRepositoryForkMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeToolImplementation) CreateRepositoryForkCallCount() int {
	fake.createRepositoryForkMutex.RLock()
	defer fake.createRepositoryForkMutex.RUnlock()
	return len(fake.createRepositoryForkArgsForCall)
}

func (fake *FakeToolImplementation) CreateRepositoryForkCalls(stub func(context.Context, *auth.Authenticator, *models.Repository, string) error) {
	fake.createRepositoryForkMutex.Lock()
	defer fake.createRepositoryForkMutex.Unlock()
	fake.CreateRepositoryForkStub = stub
}

func (fake *FakeToolImplementation) CreateRepositoryForkArgsForCall(i int) (context.Context, *auth.Authenticator, *models.Repository, string) {
	fake.createRepositoryForkMutex.RLock()
	defer fake.createRepositoryForkMutex.RUnlock()
	argsForCall := fake.createRepositoryForkArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeToolImplementation) CreateRepositoryForkArgs() []FakeToolImplementationCreateRepositoryForkArgs {
	fake.createRepositoryForkMutex.RLock()
	defer fake.createRepositoryForkMutex.RUnlock()
	args := make([]FakeToolImplementationCreateRepositoryForkArgs, len(fake.createRepositoryForkArgsForCall))
	copy(args, fake.createRepositoryForkArgsForCall)
	return args
}

func (fake *FakeToolImplementation) CreateRepositoryForkReturns(result1 error) {
	fake.createRepositoryForkMutex.Lock()
	defer fake.createRepositoryForkMutex.Unlock()
	fake.CreateRepositoryForkStub = nil
	fake.createRepositoryForkReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolImplementation) CreateRepositoryForkReturnsOnCall(i int, result1 error) {
	fake.createRepositoryForkMutex.Lock()
	defer fake.createRepositoryForkMutex.Unlock()
	fake.CreateRepositoryForkStub = nil
	if fake.createRepositoryForkReturnsOnCall == nil {
		fake.createRepositoryForkReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createRepositoryForkReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolImplementation) GetBranchControls(arg1 context.Context, arg2 models.VcsBackend, arg3 *models.Branch) (*slsa.ControlSet, error) {
	fake.getBranchControlsMutex.Lock()
	ret, specificReturn := fake.getBranchControlsReturnsOnCall[len(fake.getBranchControlsArgsForCall)]
	fake.getBranchControlsArgsForCall = append(fake.getBranchControlsArgsForCall, FakeToolImplementationGetBranchControlsArgs{arg1, arg2, arg3})
	stub := fake.GetBranchControlsStub
	fakeReturns := fake.getBranchControlsReturns
	fake.recordInvocation("GetBranchControls", []interface{}{arg1, arg2, arg3})
	fake.getBranchControlsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeToolImplementation) GetBranchControlsCallCount() int {
	fake.getBranchControlsMutex.RLock()
	defer fake.getBranchControlsMutex.RUnlock()
	return len(fake.getBranchControlsArgsForCall)
}

func (fake *FakeToolImplementation) GetBranchControlsCalls(stub func(context.Context, models.VcsBackend, *models.Branch) (*slsa.ControlSet, error)) {
	fake.getBranchControlsMutex.Lock()
	defer fake.getBranchControlsMutex.Unlock()
	fake.GetBranchControlsStub = stub
}

func (fake *FakeToolImplementation) GetBranchControlsArgsForCall(i int) (context.Context, models.VcsBackend, *models.Branch) {
	fake.getBranchControlsMutex.RLock()
	defer fake.getBranchControlsMutex.RUnlock()
	argsForCall := fake.getBranchControlsArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeToolImplementation) GetBranchControlsArgs() []FakeToolImplementationGetBranchControlsArgs {
	fake.getBranchControlsMutex.RLock()
	defer fake.getBranchControlsMutex.RUnlock()
	args := make([]FakeToolImplementationGetBranchControlsArgs, len(fake.getBranchControlsArgsForCall))
	copy(args, fake.getBranchControlsArgsForCall)
	return args
}

func (fake *FakeToolImplementation) GetBranchControlsReturns(result1 *slsa.ControlSet, result2 error) {
	fake.getBranchControlsMutex.Lock()
	defer fake.getBranchControlsMutex.Unlock()
	fake.GetBranchControlsStub = nil
	fake.getBranchControlsReturns = struct {
		result1 *slsa.ControlSet
		result2 error
	}{result1, result2}
}

func (fake *FakeToolImplementation) GetBranchControlsReturnsOnCall(i int, result1 *slsa.ControlSet, result2 error) {
	fake.getBranchControlsMutex.Lock()
	defer fake.getBranchControlsMutex.Unlock()
	fake.GetBranchControlsStub = nil
	if fake.getBranchControlsReturnsOnCall == nil {
		fake.getBranchControlsReturnsOnCall = make(map[int]struct {
			result1 *slsa.ControlSet
			result2 error
		})
	}
	fake.getBranchControlsReturnsOnCall[i] = struct {
		result1 *slsa.ControlSet
		result2 error
	}{result1, result2}
}

func (fake *FakeToolImplementation) GetBranchControlsAtCommit(arg1 context.Context, arg2 models.VcsBackend, arg3 *models.Branch, arg4 *models.Commit) (*slsa.ControlSet, error) {
	fake.getBranchControlsAtCommitMutex.Lock()
	ret, specificReturn := fake.getBranchControlsAtCommitReturnsOnCall[len(fake.getBranchControlsAtCommitArgsForCall)]
	fake.getBranchControlsAtCommitArgsForCall = append(fake.getBranchControlsAtCommitArgsForCall, FakeToolImplementationGetBranchControlsAtCommitArgs{arg1, arg2, arg3, arg4})
	stub := fake.GetBranchControlsAtCommitStub
	fakeReturns := fake.getBranchControlsAtCommitReturns
	fake.recordInvocation("GetBranchControlsAtCommit", []interface{}{arg1, arg2, arg3, arg4})
	fake.getBranchControlsAtCommitMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeToolImplementation) GetBranchControlsAtCommitCallCount() int {
	fake.getBranchControlsAtCommitMutex.RLock()
	defer fake.getBranchControlsAtCommitMutex.RUnlock()
	return len(fake.getBranchControlsAtCommitArgsForCall)
}

func (fake *FakeToolImplementation) GetBranchControlsAtCommitCalls(stub func(context.Context, models.VcsBackend, *models.Branch, *models.Commit) (*slsa.ControlSet, error)) {
	fake.getBranchControlsAtCommitMutex.Lock()
	defer fake.getBranchControlsAtCommitMutex.Unlock()
	fake.GetBranchControlsAtCommitStub = stub
}

func (fake *FakeToolImplementation) GetBranchControlsAtCommitArgsForCall(i int) (context.Context, models.VcsBackend, *models.Branch, *models.Commit) {
	fake.getBranchControlsAtCommitMutex.RLock()
	defer fake.getBranchControlsAtCommitMutex.RUnlock()
	argsForCall := fake.getBranchControlsAtCommitArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeToolImplementation) GetBranchControlsAtCommitArgs() []FakeToolImplementationGetBranchControlsAtCommitArgs {
	fake.getBranchControlsAtCommitMutex.RLock()
	defer fake.getBranchControlsAtCommitMutex.RUnlock()
	args := make([]FakeToolImplementationGetBranchControlsAtCommitArgs, len(fake.getBranchControlsAtCommitArgsForCall))
	copy(args, fake.getBranchControlsAtCommitArgsForCall)
	return args
}

func (fake *FakeToolImplementation) GetBranchControlsAtCommitReturns(result1 *slsa.ControlSet, result2 error) {
	fake.getBranchControlsAtCommitMutex.Lock()
	defer fake.getBranchControlsAtCommitMutex.Unlock()
	fake.GetBranchControlsAtCommitStub = nil
	fake.getBranchControlsAtCommitReturns = struct {
		result1 *slsa.ControlSet
		result2 error
	}{result1, result2}
}

func (fake *FakeToolImplementation) GetBranchControlsAtCommitReturnsOnCall(i int, result1 *slsa.ControlSet, result2 error) {
	fake.getBranchControlsAtCommitMutex.Lock()
	defer fake.getBranchControlsAtCommitMutex.Unlock()
	fake.GetBranchControlsAtCommitStub = nil
	if fake.getBranchControlsAtCommitReturnsOnCall == nil {
		fake.getBranchControlsAtCommitReturnsOnCall = make(map[int]struct {
			result1 *slsa.ControlSet
			result2 error
		})
	}
	fake.getBranchControlsAtCommitReturnsOnCall[i] = struct {
		result1 *slsa.ControlSet
		result2 error
	}{result1, result2}
}

func (fake *FakeToolImplementation) GetPolicyStatus(arg1 context.Context, arg2 *auth.Authenticator, arg3 *options.Options, arg4 *models.Repository) (*slsa.Control, error) {
	fake.getPolicyStatusMutex.Lock()
	ret, specificReturn := fake.getPolicyStatusReturnsOnCall[len(fake.getPolicyStatusArgsForCall)]
	fake.getPolicyStatusArgsForCall = append(fake.getPolicyStatusArgsForCall, FakeToolImplementationGetPolicyStatusArgs{arg1, arg2, arg3, arg4})
	stub := fake.GetPolicyStatusStub
	fakeReturns := fake.getPolicyStatusReturns
	fake.recordInvocation("GetPolicyStatus", []interface{}{arg1, arg2, arg3, arg4})
	fake.getPolicyStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeToolImplementation) GetPolicyStatusCallCount() int {
	fake.getPolicyStatusMutex.RLock()
	defer fake.getPolicyStatusMutex.RUnlock()
	return len(fake.getPolicyStatusArgsForCall)
}

func (fake *FakeToolImplementation) GetPolicyStatusCalls(stub func(context.Context, *auth.Authenticator, *options.Options, *models.Repository) (*slsa.Control, error)) {
	fake.getPolicyStatusMutex.Lock()
	defer fake.getPolicyStatusMutex.Unlock()
	fake.GetPolicyStatusStub = stub
}

func (fake *FakeToolImplementation) GetPolicyStatusArgsForCall(i int) (context.Context, *auth.Authenticator, *options.Options, *models.Repository) {
	fake.getPolicyStatusMutex.RLock()
	defer fake.getPolicyStatusMutex.RUnlock()
	argsForCall := fake.getPolicyStatusArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeToolImplementation) GetPolicyStatusArgs() []FakeToolImplementationGetPolicyStatusArgs {
	fake.getPolicyStatusMutex.RLock()
	defer fake.getPolicyStatusMutex.RUnlock()
	args := make([]FakeToolImplementationGetPolicyStatusArgs, len(fake.getPolicyStatusArgsForCall))
	copy(args, fake.getPolicyStatusArgsForCall)
	return args
}

func (fake *FakeToolImplementation) GetPolicyStatusReturns(result1 *slsa.Control, result2 error) {
	fake.getPolicyStatusMutex.Lock()
	defer fake.getPolicyStatusMutex.Unlock()
	fake.GetPolicyStatusStub = nil
	fake.getPolicyStatusReturns = struct {
		result1 *slsa.Control
		result2 error
	}{result1, result2}
}

func (fake *FakeToolImplementation) GetPolicyStatusReturnsOnCall(i int, result1 *slsa.Control, result2 error) {
	fake.getPolicyStatusMutex.Lock()
	defer fake.getPolicyStatusMutex.Unlock()
	fake.GetPolicyStatusStub = nil
	if fake.getPolicyStatusReturnsOnCall == nil {
		fake.getPolicyStatusReturnsOnCall = make(map[int]struct {
			result1 *slsa.Control
			result2 error
		})
	}
	fake.getPolicyStatusReturnsOnCall[i] = struct {
		result1 *slsa.Control
		result2 error
	}{result1, result2}
}

func (fake *FakeToolImplementation) SearchPullRequest(arg1 context.Context, arg2 *auth.Authenticator, arg3 *models.Repository, arg4 string) (*models.PullRequest, error) {
	fake.searchPullRequestMutex.Lock()
	ret, specificReturn := fake.searchPullRequestReturnsOnCall[len(fake.searchPullRequestArgsForCall)]
	fake.searchPullRequestArgsForCall = append(fake.searchPullRequestArgsForCall, FakeToolImplementationSearchPullRequestArgs{arg1, arg2, arg3, arg4})
	stub := fake.SearchPullRequestStub
	fakeReturns := fake.searchPullRequestReturns
	fake.recordInvocation("SearchPullRequest", []interface{}{arg1, arg2, arg3, arg4})
	fake.searchPullRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeToolImplementation) SearchPullRequestCallCount() int {
	fake.searchPullRequestMutex.RLock()
	defer fake.searchPullRequestMutex.RUnlock()
	return len(fake.searchPullRequestArgsForCall)
}

func (fake *FakeToolImplementation) SearchPullRequestCalls(stub func(context.Context, *auth.Authenticator, *models.Repository, string) (*models.PullRequest, error)) {
	fake.searchPullRequestMutex.Lock()
	defer fake.searchPullRequestMutex.Unlock()
	fake.SearchPullRequestStub = stub
}

func (fake *FakeToolImplementation) SearchPullRequestArgsForCall(i int) (context.Context, *auth.Authenticator, *models.Repository, string) {
	fake.searchPullRequestMutex.RLock()
	defer fake.searchPullRequestMutex.RUnlock()
	argsForCall := fake.searchPullRequestArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeToolImplementation) SearchPullRequestArgs() []FakeToolImplementationSearchPullRequestArgs {
	fake.searchPullRequestMutex.RLock()
	defer fake.searchPullRequestMutex.RUnlock()
	args := make([]FakeToolImplementationSearchPullRequestArgs, len(fake.searchPullRequestArgsForCall))
	copy(args, fake.searchPullRequestArgsForCall)
	return args
}

func (fake *FakeToolImplementation) SearchPullRequestReturns(result1 *models.PullRequest, result2 error) {
	fake.searchPullRequestMutex.Lock()
	defer fake.searchPullRequestMutex.Unlock()
	fake.SearchPullRequestStub = nil
	fake.searchPullRequestReturns = struct {
		result1 *models.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeToolImplementation) SearchPullRequestReturnsOnCall(i int, result1 *models.PullRequest, result2 error) {
	fake.searchPullRequestMutex.Lock()
	defer fake.searchPullRequestMutex.Unlock()
	fake.SearchPullRequestStub = nil
	if fake.searchPullRequestReturnsOnCall == nil {
		fake.searchPullRequestReturnsOnCall = make(map[int]struct {
			result1 *models.PullRequest
			result2 error
		})
	}
	fake.searchPullRequestReturnsOnCall[i] = struct {
		result1 *models.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeToolImplementation) VerifyOptionsForFullOnboard(arg1 *auth.Authenticator, arg2 *options.Options) error {
	fake.verifyOptionsForFullOnboardMutex.Lock()
	ret, specificReturn := fake.verifyOptionsForFullOnboardReturnsOnCall[len(fake.verifyOptionsForFullOnboardArgsForCall)]
	fake.verifyOptionsForFullOnboardArgsForCall = append(fake.verifyOptionsForFullOnboardArgsForCall, FakeToolImplementationVerifyOptionsForFullOnboardArgs{arg1, arg2})
	stub := fake.VerifyOptionsForFullOnboardStub
	fakeReturns := fake.verifyOptionsForFullOnboardReturns
	fake.recordInvocation("VerifyOptionsForFullOnboard", []interface{}{arg1, arg2})
	fake.verifyOptionsForFullOnboardMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeToolImplementation) VerifyOptionsForFullOnboardCallCount() int {
	fake.verifyOptionsForFullOnboardMutex.RLock()
	defer fake.verifyOptionsForFullOnboardMutex.RUnlock()
	return len(fake.verifyOptionsForFullOnboardArgsForCall)
}

func (fake *FakeToolImplementation) VerifyOptionsForFullOnboardCalls(stub func(*auth.Authenticator, *options.Options) error) {
	fake.verifyOptionsForFullOnboardMutex.Lock()
	defer fake.verifyOptionsForFullOnboardMutex.Unlock()
	fake.VerifyOptionsForFullOnboardStub = stub
}

func (fake *FakeToolImplementation) VerifyOptionsForFullOnboardArgsForCall(i int) (*auth.Authenticator, *options.Options) {
	fake.verifyOptionsForFullOnboardMutex.RLock()
	defer fake.verifyOptionsForFullOnboardMutex.RUnlock()
	argsForCall := fake.verifyOptionsForFullOnboardArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeToolImplementation) VerifyOptionsForFullOnboardArgs() []FakeToolImplementationVerifyOptionsForFullOnboardArgs {
	fake.verifyOptionsForFullOnboardMutex.RLock()
	defer fake.verifyOptionsForFullOnboardMutex.RUnlock()
	args := make([]FakeToolImplementationVerifyOptionsForFullOnboardArgs, len(fake.verifyOptionsForFullOnboardArgsForCall))
	copy(args, fake.verifyOptionsForFullOnboardArgsForCall)
	return args
}

func (fake *FakeToolImplementation) VerifyOptionsForFullOnboardReturns(result1 error) {
	fake.verifyOptionsForFullOnboardMutex.Lock()
	defer fake.verifyOptionsForFullOnboardMutex.Unlock()
	fake.VerifyOptionsForFullOnboardStub = nil
	fake.verifyOptionsForFullOnboardReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolImplementation) VerifyOptionsForFullOnboardReturnsOnCall(i int, result1 error) {
	fake.verifyOptionsForFullOnboardMutex.Lock()
	defer fake.verifyOptionsForFullOnboardMutex.Unlock()
	fake.VerifyOptionsForFullOnboardStub = nil
	if fake.verifyOptionsForFullOnboardReturnsOnCall == nil {
		fake.verifyOptionsForFullOnboardReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyOptionsForFullOnboardReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolImplementation) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeToolImplementation) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeToolImplementation) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
