# SPDX-FileCopyrightText: Copyright 2025 The SLSA Authors
# SPDX-License-Identifier: Apache-2.0
---
name: Go Tests (sourcetool)

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: carabiner-dev/actions/go/versions@440c76def32d40be101b68d1f6a6b284b79aa74c # v1.1.2
        id: go-versions

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ steps.go-versions.outputs.latest }}
          check-latest: true
          cache: false

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@a47c93e0b1648d5651a065437926377d060baa99 # v1.50.0

      - name: Setup protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # @v3.0.0

      - name: Run Go tests
        run: |
          go test -v ./...

      - name: Check generated fakes
        run: |
          hack/verify-fakes.sh

      - name: Check protobuf generated codew
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          hack/verify-protos.sh
